remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
description: [Thoughts on technical writing and resources for technical writers]
show_downloads: [false]
